version: '3.8'

services:

  db1:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=demo_1
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./docker/mysql/db1:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  db2:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=demo_3
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=33066 
    volumes:
      - "./docker/mysql/db2:/docker-entrypoint-initdb.d"
    ports:
      - "33066:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOSTS=db1,db2
      - PMA_PORTS=3306,33066

  apache:
    build: "./docker/apache"
    volumes:
      - "./src:/var/www/html"
    ports:
      - 80:80
